# Generated by Django 5.2.12 on 2026-03-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatushistory',
            name='new_status',
            field=models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждён'), ('processing', 'В обработке'), ('shipped', 'Отправлен'), ('delivered', 'Доставлен'), ('completed', 'Завершён'), ('cancelled', 'Отменён'), ('refunded', 'Возврат')], max_length=20, verbose_name='Новый статус'),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='old_status',
            field=models.CharField(blank=True, choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждён'), ('processing', 'В обработке'), ('shipped', 'Отправлен'), ('delivered', 'Доставлен'), ('completed', 'Завершён'), ('cancelled', 'Отменён'), ('refunded', 'Возврат')], max_length=20, verbose_name='Предыдущий статус'),
        ),
    ]
