# Generated by Django 5.2.12 on 2026-03-21 23:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Иконка (CSS класс)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Изображение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Категория услуг',
                'verbose_name_plural': 'Категории услуг',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL')),
                ('description', models.TextField(verbose_name='Описание')),
                ('short_description', models.CharField(blank=True, max_length=300, verbose_name='Краткое описание')),
                ('pricing_type', models.CharField(choices=[('fixed', 'Фиксированная цена'), ('hourly', 'Почасовая оплата'), ('negotiable', 'По договорённости')], default='fixed', max_length=20, verbose_name='Тип цены')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена')),
                ('price_per_hour', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена за час')),
                ('min_hours', models.PositiveIntegerField(default=1, verbose_name='Минимум часов')),
                ('duration_hours', models.PositiveIntegerField(default=1, verbose_name='Примерная длительность (часов)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Изображение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Популярная')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.servicecategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Номер заявки')),
                ('status', models.CharField(choices=[('pending', 'Ожидает обработки'), ('confirmed', 'Подтверждена'), ('assigned', 'Мастер назначен'), ('in_progress', 'Выполняется'), ('completed', 'Выполнена'), ('cancelled', 'Отменена')], default='pending', max_length=20, verbose_name='Статус')),
                ('urgency', models.CharField(choices=[('normal', 'Обычная'), ('urgent', 'Срочная'), ('emergency', 'Экстренная')], default='normal', max_length=20, verbose_name='Срочность')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание проблемы')),
                ('contact_name', models.CharField(max_length=200, verbose_name='Контактное лицо')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('address_city', models.CharField(max_length=100, verbose_name='Город')),
                ('address_street', models.CharField(max_length=300, verbose_name='Адрес')),
                ('preferred_date', models.DateField(verbose_name='Желаемая дата')),
                ('preferred_time_from', models.TimeField(verbose_name='Время с')),
                ('preferred_time_to', models.TimeField(verbose_name='Время до')),
                ('scheduled_date', models.DateField(blank=True, null=True, verbose_name='Назначенная дата')),
                ('scheduled_time', models.TimeField(blank=True, null=True, verbose_name='Назначенное время')),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Предварительная стоимость')),
                ('final_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Итоговая стоимость')),
                ('hours_worked', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Отработано часов')),
                ('customer_notes', models.TextField(blank=True, verbose_name='Примечания клиента')),
                ('technician_notes', models.TextField(blank=True, verbose_name='Заметки мастера')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Заметки администратора')),
                ('photo1', models.ImageField(blank=True, null=True, upload_to='service_requests/', verbose_name='Фото 1')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='service_requests/', verbose_name='Фото 2')),
                ('photo3', models.ImageField(blank=True, null=True, upload_to='service_requests/', verbose_name='Фото 3')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата выполнения')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отмены')),
                ('related_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests', to='orders.order', verbose_name='Связанный заказ')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='services.service', verbose_name='Услуга')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_requests', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Заявка на услугу',
                'verbose_name_plural': 'Заявки на услуги',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequestHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=20, verbose_name='Предыдущий статус')),
                ('new_status', models.CharField(max_length=20, verbose_name='Новый статус')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='services.servicerequest', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'История статуса заявки',
                'verbose_name_plural': 'История статусов заявок',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, verbose_name='О себе')),
                ('experience_years', models.PositiveIntegerField(default=0, verbose_name='Опыт работы (лет)')),
                ('certifications', models.TextField(blank=True, verbose_name='Сертификаты')),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ставка в час')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступен')),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Рейтинг')),
                ('completed_orders', models.PositiveIntegerField(default=0, verbose_name='Выполнено заказов')),
                ('specializations', models.ManyToManyField(related_name='technicians', to='services.servicecategory', verbose_name='Специализации')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='technician_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Мастер',
                'verbose_name_plural': 'Мастера',
            },
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests', to='services.technician', verbose_name='Мастер'),
        ),
    ]
