# Generated by Django 5.2.12 on 2026-03-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequesthistory',
            name='new_status',
            field=models.CharField(choices=[('pending', 'Ожидает обработки'), ('confirmed', 'Подтверждена'), ('assigned', 'Мастер назначен'), ('in_progress', 'Выполняется'), ('completed', 'Выполнена'), ('cancelled', 'Отменена')], max_length=20, verbose_name='Новый статус'),
        ),
        migrations.AlterField(
            model_name='servicerequesthistory',
            name='old_status',
            field=models.CharField(blank=True, choices=[('pending', 'Ожидает обработки'), ('confirmed', 'Подтверждена'), ('assigned', 'Мастер назначен'), ('in_progress', 'Выполняется'), ('completed', 'Выполнена'), ('cancelled', 'Отменена')], max_length=20, verbose_name='Предыдущий статус'),
        ),
    ]
