# Generated by Django 5.2.12 on 2026-04-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, unique=True, verbose_name='URL'),
        ),
    ]
